<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsPackable>False</IsPackable>
    <UseWPF>True</UseWPF>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <Description>SD.Framework OpenCV客户端</Description>
  </PropertyGroup>

  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>Full</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="favicon.ico" />
    <Resource Include="Content\Images\OpenCV.png" />
    <Content Include="$(OpenCvSharp4ExternalNativeDlls)\win-x86\native\*.*">
      <Visible>False</Visible>
    </Content>
    <Content Include="$(OpenCvSharp4ExternalNativeDlls)\win-x64\native\*.*">
      <Visible>False</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.23.2" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="6.2.1" />
    <PackageReference Include="FluentWPF" Version="0.10.2" />
    <PackageReference Include="BusyIndicator" Version="1.9.0">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
    <PackageReference Include="MrAdvice" Version="2.19.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.1" />
    <PackageReference Include="SD.Common" Version="4.0.0" />
    <PackageReference Include="SD.Toolkits.Serialization" Version="4.0.0" />
    <PackageReference Include="SD.IOC.Core" Version="1.4.0" />
    <PackageReference Include="SD.Infrastructure" Version="4.0.0" />
    <PackageReference Include="SD.Infrastructure.WPF" Version="4.0.0" />
    <PackageReference Include="SD.Infrastructure.WPF.Caliburn" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SD.OpenCV.Primitives\SD.OpenCV.Primitives.csproj" />
    <ProjectReference Include="..\SD.OpenCV.OnnxRuntime\SD.OpenCV.OnnxRuntime.csproj" />
    <ProjectReference Include="..\SD.OpenCV.SkiaSharp\SD.OpenCV.SkiaSharp.csproj" />
  </ItemGroup>
</Project>
