<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <IsPackable>False</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Content\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="$(OpenCvSharp4ExternalNativeDlls)\win-x86\native\*.*">
      <Visible>False</Visible>
    </Content>
    <Content Include="$(OpenCvSharp4ExternalNativeDlls)\win-x64\native\*.*">
      <Visible>False</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net48'))">
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.23.2" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SD.OpenCV.Primitives\SD.OpenCV.Primitives.csproj" />
    <ProjectReference Include="..\SD.OpenCV.OnnxRuntime\SD.OpenCV.OnnxRuntime.csproj" />
    <ProjectReference Include="..\SD.OpenCV.SkiaSharp\SD.OpenCV.SkiaSharp.csproj" />
  </ItemGroup>
</Project>
