<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>SD.Framework OpenCV OnnxRuntime扩展</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Content\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Content\Labels\*.*">
      <Pack>True</Pack>
      <PackagePath>content\Content\Labels\</PackagePath>
    </None>
    <None Include="Content\Build\Package.props">
      <Pack>True</Pack>
      <PackagePath>build\net462\$(PackageId).props</PackagePath>
    </None>
    <None Include="Content\Build\Package.props">
      <Pack>True</Pack>
      <PackagePath>build\netstandard2.0\$(PackageId).props</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.23.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SD.OpenCV.Primitives\SD.OpenCV.Primitives.csproj" />
  </ItemGroup>
</Project>
